Traceback (most recent call last):
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aaron/code/Olat_Tamid/venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import Markdown
from tanakh_reader import verse, chapter, verses

text = f"""{verse('psalms', 5, 8)[1]} {verse('psalms', 55, 15)[1]}"""

Markdown(text)

------------------


Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m~/code/Olat_Tamid/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3577[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0;36m  Cell [0;32mIn[1], line 2[0;36m
[0;31m    from tanakh_reader import verse, chapter, verses[0;36m

[0;36m  File [0;32m~/code/Olat_Tamid/Olat_Tamid/tanakh_reader.py:11[0;36m[0m
[0;31m    return "Oops something went wrong"[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m expected an indented block after 'if' statement on line 10


